### ISSUE TITLE
保活不成功

### ISSUE THREAD

**Issue by SuNianByCh** [wangshihu123/DaemonLibrary#1]
1.魅蓝6 
系统型号：Flyme 7.0.1.1A 
Android版本：7.0
现象：没有办法打开服务。
2.华为mate 8
 Android 版本：8.0.0
现象：没有办法保活。

**Comment by ShihooWang** [comment]
1.魅蓝6
  无法打开服务，指的是打开对应的权限设置吗？
2.华为mate 8
Android 版本：8.0.0
华为系列的高版本系列，如果手动清内存，很大概率挂掉的。
如果正常退到后台，不清内存，我测试过mate10 P20 V20等是可以的。在任务卡片上能看到无声音乐播放。

**Comment by ShihooWang** [comment]
> 1.魅蓝6
> 系统型号：Flyme 7.0.1.1A
> Android版本：7.0
> 现象：没有办法打开服务。
> 2.华为mate 8
> Android 版本：8.0.0
> 现象：没有办法保活。

期待你的反馈，请多指教！

**Comment by SuNianByCh** [comment]
1.魅蓝服务都没有启动，log没有输出。
2.华为mate8是强杀

**Comment by SuNianByCh** [comment]
魅蓝debug下也没有看到进入相应的 service.onstart()

**Comment by ShihooWang** [comment]
> 魅蓝debug下也没有看到进入相应的 service.onstart()

因为是多进程，一般来不及debug的，还是log日志相对好一些。

**Comment by ShihooWang** [comment]
> 1.魅蓝服务都没有启动，log没有输出。
> 2.华为mate8是强杀
魅族开不起服务，难道定制的Rom另要权限吗。。。要到魅族开发者官网查查。。。

**Comment by SuNianByCh** [comment]
刚查找一下魅蓝原因，是我今天升级系统了。关闭了日志输出。
你的保活对强杀都不起作用吧？

**Comment by ShihooWang** [comment]
> 刚查找一下魅蓝原因，是我今天升级系统了。关闭了日志输出。
> 你的保活对强杀都不起作用吧？

6.0及以下的强杀可以保活的，这个和不同厂家的rom也有关系的。
