### ISSUE TITLE
无

### ISSUE THREAD

**Issue by dxp2020** [wangshihu123/DaemonLibrary#17]

**Comment by dxp2020** [comment]
目前，在高版本的Android系统中已经失效，因为高版本的Android系统规定应用必须在系统开机后运行一次才能监听这些系统广播，一般而言，应用被系统杀死后，基本无法接收系统广播。

**Comment by ShihooWang** [comment]
Root后，安装的系统级别的应用才能检测到开机广播。

**Comment by zhangwilling** [comment]
小米开启【自启动】应该也是可以的，设备是 红米7 android 9，我这边没用太多黑科技，自己做了一个简单的前台服务。
