### ISSUE TITLE
服务通知栏的的util要开放一下

### ISSUE THREAD

**Issue by FlandreUNX** [wangshihu123/DaemonLibrary#19]
一个大大的"保"字+主服务+运行中..
作者麻烦重写一下接口吧.让用户可以随意修改通知栏,

**Comment by ShihooWang** [comment]
多谢你的反馈，v1.2.1版本已增加接口设置通知栏UI。
具体可以参考Demo的App类中的代码。
非常感谢！

**Comment by FlandreUNX** [comment]
nice!
