### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by yxj1990** [wangshihu123/DaemonLibrary#2]
每次锁屏，再次打开都黑屏，点击返回键才能正常

**Comment by ShihooWang** [comment]
因为锁屏的时候使用了1像素的Activity，在监听到解锁的时候再去销毁掉。
如果锁屏后再打开黑屏且需要点击返回键才能正常，那说明没有监听到解锁这个动作。
麻烦你看下log日志确认下。
另外，方便说一下手机的型号和对应的Android版本吗？

**Comment by yxj1990** [comment]
确实是1像素activity没有销毁的问题，是我之前自己写的1像素的问题，抱歉

**Comment by ShihooWang** [comment]
解决了就好！

**Comment by yxj1990** [comment]
您有没有遇到过，小米手机省点模式，后端无法定位，开启不限电模式后定位就可以；其他机型后端都可以定位，谢谢啦

**Comment by ShihooWang** [comment]
先说个高德地图的定位在8.0有所调整：https://lbs.amap.com/api/android-location-sdk/guide/utilities/permision_8
小米这个情况，确实要开始不限电模式。
还有华为的后台运行管理，如果不开启手动管理，锁屏后也是定位不到的。
厂商定制的rom很让人头痛。

**Comment by yxj1990** [comment]
高德这个我也用了，但是我看到其他的应用有不限电在后端也可以记录的，比如两步路app，不清楚是用了什么办法

**Comment by ShihooWang** [comment]
我看了一下，两步路APP几乎把市面上手机的设置权限都使用了，在manifest申请了修改设置的权限。（9000+行的manifest。。。）
我贴一部分：
uses-permission：
android:name="com.oppo.launcher.permission.READ_SETTINGS"
android:name="com.oppo.launcher.permission.WRITE_SETTINGS" 
android:name="com.miui.mihome2.permission.READ_SETTINGS"
android:name="com.miui.mihome2.permission.WRITE_SETTINGS"
然后在对应手机上做设置（猜测），这些定制化的权限，一般开发者都不知道的，这需要费很大的劲才能搞到，更别说去代码动态设置了。
