### ISSUE TITLE
试了一台华为8.0的手机，锁屏立马失效，想问下你们认为APP还在后台运行的依据是什么？

### ISSUE THREAD

**Issue by TracyEminem** [wangshihu123/DaemonLibrary#25]
是通过连接数据线查看APP的LOG吗？如果是查看打印Log的话，这种方式是有问题的，我是在savedata这个方法里面请求一个后台的接口，带上请求的时间，锁屏后或者退到后台后就不会再Call api了

**Comment by ShihooWang** [comment]
1.验证程序是否在后台运行：使用间隔计数的方式，比如说30秒计数一次。
2.确认下手机是否限制了应用后台网络请求的权限

**Comment by TracyEminem** [comment]
搞定了，原来要手动开启锁屏后网络不会断的那个设置才可以发送网络请求，这个库很好用，谢谢
