### ISSUE TITLE
联想Z5，Android8.1，保活失败，是需要什么权限吗？之前在华为荣耀的8.0手机上成功了

### ISSUE THREAD

**Issue by TracyEminem** [wangshihu123/DaemonLibrary#27]
如题，我们的用户是可控的，是我们自己的员工使用联想的Z5手机，所以可以让他们配合开启一些权限或者相关的操作，有什么可以增强这个效果的方案或者建议吗？我试着在每次网络请求后持有wakelock后来发现可以实现锁屏后的定时网络请求了，但是似乎这个方案看起来比较脆弱。

**Comment by ShihooWang** [comment]
持有wakelock锁，经常会被系统提示耗电。
既然用户可控，不妨试着手动开启手机系统白名单。

**Comment by TracyEminem** [comment]
OK，十分感谢
