### ISSUE TITLE
网络断开的时候也会触发唤醒吗？

### ISSUE THREAD

**Issue by yb0312** [wangshihu123/DaemonLibrary#4]
04-17 23:39:42.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 5
04-17 23:39:43.153 29735-29735/com.shihoo.daemonlibrary:receiver D/wsh-daemon: 安全启动服务。。: WatchDogService
04-17 23:39:43.329 29735-29735/com.shihoo.daemonlibrary:receiver D/wsh-daemon: 安全启动服务。。: WatchDogService
04-17 23:39:43.450 29735-29735/com.shihoo.daemonlibrary:receiver D/wsh-daemon: 安全启动服务。。: WatchDogService
04-17 23:39:45.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 6
04-17 23:39:46.741 29735-29735/com.shihoo.daemonlibrary:receiver D/wsh-daemon: 安全启动服务。。: WatchDogService
04-17 23:39:48.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 7
04-17 23:39:51.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 8
04-17 23:40:21.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 18
04-17 23:40:21.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 保存数据到磁盘。
04-17 23:40:21.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon:    采集数据  saveCount = 0
04-17 23:40:24.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 19
04-17 23:40:24.534 29632-29632/com.shihoo.daemonlibrary:watch D/wsh-daemon: JobSchedulerService  onStartJob 启动。。。。
04-17 23:40:24.536 29632-29632/com.shihoo.daemonlibrary:watch D/wsh-daemon: 安全启动服务。。: WatchDogService
04-17 23:40:24.582 29632-29667/com.shihoo.daemonlibrary:watch D/wsh-daemon: 安全启动服务。。: PlayMusicService
04-17 23:40:27.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 20
04-17 23:40:30.114 29601-29648/com.shihoo.daemonlibrary:work D/wsh-daemon: 每 3 秒采集一次数据... count = 21
从日志上来看，网络断开后，启动WatchDogService四次，然后重启服务线程了？

**Comment by ShihooWang** [comment]
是的，该receiver在manifest中注册了对网络变化的监听。
receiver进程中打印了四次启动服务的log日志，这代表着该进程的BroadcastReceiver的onReceive方法执行了四次。
但是这并不是真的启动了WatchDogService四次。如果WatchDogService已经开启了，再去启动它，就会执行Service生命周期的onStartCommand()方法，WatchDogService，运行在watch进程中。
程序中有主进程、work进程、watch进程、receive进程，项目中使用多进程来分散内存占用，避免OOM问题，降低被系统杀死的概率，有利于保活。

**Comment by yb0312** [comment]
如何设置网络断开后，不重启服务呢？

**Comment by ShihooWang** [comment]
1.这个并没有重启服务。重启服务会执行Service的oncreate方法。这里的log日志只是去启动服务，如果服务已经开启了，会执行onStartCommand()方法。
2.可以在广播监听的onReceive方法判断当前为网络断开的状态，或者干脆取消对网络变化的监听。

**Comment by yb0312** [comment]
我在测试中，会偶发重启服务的情况。
还有AbsWorkService启动后，可以拿到它的binder吗？我在MainActivity中需要调用service的数据，同时也要向service发送数据。在workservice中，有如下代码：
` @Override
    public IBinder onBindService(Intent intent, Void v) {
        // 此处必须有返回，否则绑定无回调
        return new Messenger(new Handler()).getBinder();
    }`

**Comment by ShihooWang** [comment]
AbsWorkService可以被多次绑定，多次执行onbind方法。通过onbind方法返回binder。
每个绑定的activity可以通过binder拿到service的实例或者通过binder调用service方法。
这里你可以在MainWorkService的onBindService方法中返回自己需要的Messager。用来处理消息（取数据和读数据）。
我的另一个文章 ：https://blog.csdn.net/hello_json/article/details/79815320 （
android进程通信值Messenger和AIDL的区别）

**Comment by yb0312** [comment]
有例程可以参考下吗？我看源代码DaemonEnv.startServiceSafely实际上执行的startService而不是bindService

**Comment by yb0312** [comment]
我尝试用bindService来启动服务，发现watch Service不能启动，而且work Service中程序也没有运行

**Comment by ShihooWang** [comment]
是的，DaemonEnv.startServiceSafely执行了startService，但是会紧接着去绑定Service。
这里使用Intent去startService，方便其他对象去绑定这个Service。
目的是让这个Service被多次绑定。

使用bindService应该也是可以的，可以检查下代码。或者是把你的代码贴出来，让我也学习下。

**Comment by yb0312** [comment]
代码如下：
`Intent intent = new Intent(MainActivity.this, MainService.class);
MainActivity.this.bindService(intent,conn, Context.BIND_AUTO_CREATE);
ServiceConnection conn =new ServiceConnection() {
        @Override
        public void onServiceConnected(ComponentName name, IBinder service) {
            mService = new Messenger(service);
        }

        @Override
        public void onServiceDisconnected(ComponentName name) {

        }
    };`

**Comment by ShihooWang** [comment]
是的 你以Activity的bindService方法启动，并不会开启watch Service，且work Service中没有执行对应的work。
因为用来的保活的Service通常在后台不是由Activity 去bindService开启的，所以当时我设计的时候就不支持这种情况，如果你有需要的话，可以自己在源码上修改。
