### ISSUE TITLE
基本所有手机划掉卡片 基本都是干掉进程和服务的 请问如何这样是不行吗

### ISSUE THREAD

**Issue by yuzhongrong** [wangshihu123/DaemonLibrary#6]

**Comment by ShihooWang** [comment]
你好，你是想说使用ActivityManager类的removeTask方法来清理任务吗？
这个方法和API版本有关系
21版本及以下，可以选择关掉对应的栈或者杀掉进程（这个和手机厂家设置及CPU架构有关系）。
22版本及以上，系统会直接杀死进程。

**Comment by yuzhongrong** [comment]
也就是说 22以上 是无法做咯
