### ISSUE TITLE
神隐模式和自启动

### ISSUE THREAD

**Issue by douyahaha** [wangshihu123/DaemonLibrary#7]
有什么方法可以获取已经关闭了神隐模式和打开了自启动吗

**Comment by ShihooWang** [comment]
你好，这个我也去厂家官网找过，然而没有结果。。。。




------------------ 原始邮件 ------------------
发件人: "douyahaha"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 上午9:50
收件人: "ShihooWang/DaemonLibrary"<DaemonLibrary@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ShihooWang/DaemonLibrary] 神隐模式和自启动 (#7)




有什么方法可以获取已经关闭了神隐模式和打开了自启动吗

**Comment by douyahaha** [comment]
好的，我也是找了一圈，无果，这来问问

**Comment by douyahaha** [comment]
这个1像素会卡屏吗，我这个整了这个服务之后，每次都卡屏

**Comment by ShihooWang** [comment]
你好，卡屏的情况应该是1像素的Activity没有主动被销毁，请检查确认一下逻辑。
